parameters:
  - name: stage
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: condition
    type: string
    default: succeeded()
  - name: resource
    type: string
  - name: serviceConnection
    type: string
  - name: rgName
    type: string
  - name: infraPath
    type: string
  - name: location
    type: string
  - name: owner
    type: string
  - name: costCenter
    type: string
  - name: application
    type: string
  - name: desc
    type: string
  - name: repo
    type: string
  - name: appShort
    type: string
  - name: domainShort
    type: string
  - name: version
    type: string
  - name: env
    type: string
    values:
      - dev
      - acc
      - prod
    default: dev

stages:
  - stage: "${{ parameters.stage }}"
    displayName: "Stage: Provision Infrastructure - ${{ parameters.resource }}"
    dependsOn: "${{ parameters.dependsOn }}"
    condition: "${{ parameters.condition }}"
    jobs:
      - template: "../jobs/job-deploy-infra.yml@self"
        parameters:
          job: "JobDeployInfrastructure"
          jobResources: "${{ parameters.resource }}"
          serviceConnection: "${{ parameters.serviceConnection }}"
          infraPath: "${{ parameters.infraPath }}"
          rgName: ${{ parameters.rgName }}
          location: ${{ parameters.location }}
          overrideParameters: >-
            -owner "${{ parameters.owner }}"
            -costCenter "${{ parameters.costCenter }}"
            -application "${{ parameters.application }}"
            -descp "${{ parameters.desc }}"
            -repo "${{ parameters.repo }}"
            -appShort "${{ parameters.appShort }}"
            -domainShort "${{ parameters.domainShort }}"
            -env "${{ parameters.env }}"
            -version "${{ parameters.version }}"
