trigger: none

parameters:
  - name: variableGroup
    type: string
    default: vg-pfu-infrastructure
  - name: serviceConnection
    type: string
    default: Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)
  - name: environment
    type: string
    values:
      - dev
      - acc
      - prod

variables:
  - group: ${{ parameters.variableGroup }}
  - name: version
    value: 001
  - name: rgName
    value: "rg-$(companyShort)-$(domainShort)-$(appShort)-$(locationAbbr)-${{ parameters.environment }}-$(version)"

stages:
  - template: "./templates/stages/stage-deploy-infra.yml@self"
    parameters:
      stage: StageProvisionInfrastructureLogAnalytics
      resource: "Log Analytics"
      serviceConnection: "${{ parameters.serviceConnection }}"
      rgName: "$(rgName)"
      infraPath: "infra/loganalytics"
      location: "$(location)"
      owner: "$(owner)"
      costCenter: "$(costCenter)"
      application: "$(application)"
      desc: "$(descp)"
      repo: "$(repo)"
      appShort: "$(appShort)"
      domainShort: "$(domainShort)"
      version: "$(version)"
      env: "${{ parameters.environment }}"

  - template: "./templates/stages/stage-deploy-infra.yml@self"
    parameters:
      stage: StageProvisionInfrastructureDataFactory
      dependsOn:
        - StageProvisionInfrastructureLogAnalytics
      condition: succeeded()
      resource: "Data Factory"
      serviceConnection: "${{ parameters.serviceConnection }}"
      rgName: "$(rgName)"
      infraPath: "infra/data-factory"
      location: "$(location)"
      owner: "$(owner)"
      costCenter: "$(costCenter)"
      application: "$(application)"
      desc: "$(desc)"
      repo: "$(repo)"
      appShort: "$(appShort)"
      domainShort: "$(domainShort)"
      version: "$(version)"
      env: "${{ parameters.environment }}"

  # - stage: StageProvisionInfrastructureLogAnalytics
  #   displayName: "Stage: Provision InfraStructure - Log Analytics"
  #   jobs:
  #     - job: JobProvisionInfrastructureLogAnalytics
  #       displayName: "Job: Provision Infrstructure - Log Analytics"
  #       steps:
  #         - task: AzurePowerShell@5
  #           inputs:
  #             azureSubscription: "${{parameters.serviceConnection}}"
  #             ScriptType: "FilePath"
  #             ScriptPath: "$(System.DefaultWorkingDirectory)/scripts/compile-bicep-to-arm.ps1"
  #             ScriptArguments: "
  #               -filePath $(System.DefaultWorkingDirectory)/infra/loganalytics `
  #               -bicepTemplate main.bicep `
  #               -outFile main.json"
  #             azurePowerShellVersion: "LatestVersion"

  #         - task: AzureResourceManagerTemplateDeployment@3
  #           inputs:
  #             deploymentScope: "Resource Group"
  #             AzureResourceManagerConnection: "${{parameters.serviceConnection}}"
  #             action: "Create Or Update Resource Group"
  #             resourceGroupName: "rg-$(companyShort)-$(domainShort)-$(appShort)-$(locationAbbr)-${{ parameters.environment }}-$(version)"
  #             location: "$(location)"
  #             templateLocation: "Linked artifact"
  #             csmFile: "infra/loganalytics/main.json"
  #             deploymentMode: "Incremental"
  #             overrideParameters: >-
  #               -owner "$(owner)"
  #               -costCenter "$(costCenter)"
  #               -application "$(application)"
  #               -descp "$(desc)"
  #               -repo "$(repo)"
  #               -appShort "$(appShort)"
  #               -domainShort "$(domainShort)"
  #               -env "${{ parameters.environment }}"
  #               -version "$(version)"

  # - stage: StageProvisionInfrastructureDataFactory
  #   displayName: "Stage: Provision InfraStructure - Data Factory"
  #   dependsOn: StageProvisionInfrastructureLogAnalytics
  #   condition: succeeded()
  #   jobs:
  #     - job: JobProvisionInfrastructureDataFactory
  #       displayName: "Job: Provision Infrstructure - Data Factory"
  #       steps:
  #         - task: AzurePowerShell@5
  #           inputs:
  #             azureSubscription: "${{parameters.serviceConnection}}"
  #             ScriptType: "FilePath"
  #             ScriptPath: "$(System.DefaultWorkingDirectory)/scripts/compile-bicep-to-arm.ps1"
  #             ScriptArguments: "
  #               -filePath $(System.DefaultWorkingDirectory)/infra/data-factory `
  #               -bicepTemplate main.bicep `
  #               -outFile main.json"
  #             azurePowerShellVersion: "LatestVersion"

  #         - task: AzureResourceManagerTemplateDeployment@3
  #           inputs:
  #             deploymentScope: "Resource Group"
  #             AzureResourceManagerConnection: "${{parameters.serviceConnection}}"
  #             action: "Create Or Update Resource Group"
  #             resourceGroupName: "rg-$(companyShort)-$(domainShort)-$(appShort)-$(locationAbbr)-${{ parameters.environment }}-$(version)"
  #             location: "$(location)"
  #             templateLocation: "Linked artifact"
  #             csmFile: "infra/data-factory/main.json"
  #             deploymentMode: "Incremental"
  #             overrideParameters: >-
  #               -owner "$(owner)"
  #               -costCenter "$(costCenter)"
  #               -application "$(application)"
  #               -descp "$(desc)"
  #               -repo "$(repo)"
  #               -appShort "$(appShort)"
  #               -domainShort "$(domainShort)"
  #               -env "${{ parameters.environment }}"
  #               -version "$(version)"
